### ISSUE TITLE
diy2.sh优化

### ISSUE THREAD

**Issue by Cathgao** [Joecaicai/Actions-OpenWrt#7]
diy2.sh中的
`git clone https://github.com/vernesong/OpenClash.git package/OpenClash`
可改为
`git clone -b master --depth 1 https://github.com/vernesong/OpenClash.git package/luci-app-openclash`
这个仓库塞了非常多的二进制文件，完整拉取需要5GB空间，不仅浪费时间空间也没必要。

**Comment by Joecaicai** [comment]
好的嘞，谢谢大哥指点！
